title: Patrick James Lee Gonzaga # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An accomplished Software Engineer with more than 15 years of rich hands-on knowledge in the IT field will be a welcome addition to your company's hard-working team, instrumental in achieving required results the soonest possible time. 
  <br><br>
  One of the greatest achievements was being a Team Lead in implementing SAP and interfacing with all our programs with tight budget and schedule. 
  <br><br>
  <a href="www.linkedin.com/in/patrick-gonzaga">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 272805087 # your Google Analytics tracking ID here
